### ISSUE TITLE
How do I change the name of the driver for customization?

### ISSUE THREAD

**Issue by Filmengineers** [terminal29/Simple-OpenVR-Driver-Tutorial#10]
I've been trying to change the name of the driver from "example" to "myownname". But i'm unable to find a way to do it. It simply creates folders under the name of "example".

Any help would be appreciated.

Thanks,
Vivek

**Comment by terminal29** [comment]
Not sure if you fixed this, I haven't worked on the driver in a while but I'm fairly sure you have to set it in:
- `driver_files/driver/example` rename this folder to `myownname`
- `driver_files/driver/example/driver.vrdrivermanifest` rename `name` to `myownname
- `CMakeLists.txt` change `set(DRIVER_NAME "example")` to set(DRIVER_NAME "myownname")
