### ISSUE TITLE
Setting debug mode to "vrstartup"?

### ISSUE THREAD

**Issue by RensTillmann** [terminal29/Simple-OpenVR-Driver-Tutorial#11]
Hi, in the readme it states:

"Set the program the project should run in debug mode to vrstartup (Usually located C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64\vrstartup.exe). Now we can start up SteamVR without needing to go through Steam, and can properly startup all the other programs vrserver needs."

I am confused, what does "the program" imply here? And what does "project" imply?
Should I configure this somewhere in Visual Studio? Sorry if it's  stupid question, I never used Visual Studio before.

**Comment by terminal29** [comment]
This is where you set it. You can get to here by right clicking the project -> Properties -> Debugging
![image](https://user-images.githubusercontent.com/20899505/107462599-2c7d0280-6ba8-11eb-8f9b-0c25bab42d48.png)

**Comment by RensTillmann** [comment]
Thanks a bunch! I have worked on it yesterday. What I have created so far is the following (and thanks to your tutorial I was able to setup the custom driver):
- I have a mobile app that sends it's sensor data via TCP to a golang server I setup on my local computer. Right now it's sends data via Wifi, perhaps bluetooth might be better/faster (not sure).
- The golang server then reads the data, and does whatever it needs to do to determine if the user is walking in place
- Then stores a value into a file (between -1 and 1) to determine the walking speed.
- Then with C++ and the custom driver (that I was able to create thanks to your tutorial/guid) I was able to modify it so that it reads out this file, and based on whatever value is in it the walking speed is determined and set as the trackpad/joystick value.

I tested it, and it's working quite good. Obviously I just did a simple test, so the data still needs to be filtered out nicely with some algorithm. I am going to try to detect the following "poses" from the sensor data. I will build some sort of calibration method so it knows some sort of boundaries (not sure yet).
- standing still
- sneaking (slow walking)
- walking (normal speed)
- running (quickly walking)
- sprinting (full speed)

If I can get it working nicely, the only thing you would need is a mobile phone with sensors.
Still lot of work to do, but it looks promising so far 👍

**Comment by terminal29** [comment]
Sounds like a cool project you have going. If you end up releasing it please let me know, I’d love to take a look 😁.

**Comment by RensTillmann** [comment]
I will do that for sure, I hope I can make it work so it lives up to my own expectations, I know there are many locomotion options out there, I also ordered a Kat Loco S. But I read that many people do not like it that much for several reasons.

At least now I can create something that is completely to my own liking (hopefully).
For instance I could use 2 phones, or I could add some code that detects if I am leaning backwards, so that I can walk backwards too. And maybe I can add some technique to also detect if I'd want to strafe. I was thinking about putting something on both arms. So that if you lift up your left "elbow" you strafe left. And visa versa. Or a different way. Not sure yet.
Will see how things play out. 👍

**Comment by ReadieFur** [comment]
Hi there, I have a problem that is somewhat related to this as it is about debugging, its not a huge problem but more of an inconvenience that I was wondering if you knew how to resolve. When I start debugging the program, I always get a `breakpoint or similar call` that is raised inside of vrserver.exe, the reason this is annoying is that I have no vrserver.pdb file so VisualStudio pauses every time I launch the vrstartup.exe app. I have "Just My Code" enabled in the global VS settings however I can't seem to get around this issue. Any ideas on how to resolve this? Thanks.
