### ISSUE TITLE
IVRVirtualDisplay

### ISSUE THREAD

**Issue by umutbaser** [terminal29/Simple-OpenVR-Driver-Tutorial#2]
Can you add virtual display

**Comment by terminal29** [comment]
Yes, some time i the near future I will be updating the tutorial with some more stuff. If you really need some code to copy-paste, take a look at some of my other steamvr drivers as they have hmd code which works.

**Comment by umutbaser** [comment]
Actually I can't found a lot of information about IVRVirtualDisplay Interface. I have already my own driver but I want to use IVRVirtualDisplay Interface instead of IVRDisplayComponent.

**Comment by terminal29** [comment]
Oh sorry, I'll take a look at IVRVirtualDisplay as well then.

**Comment by terminal29** [comment]
From a bit of research, it seems like IVRVirtualDisplay is what you would implement if you don't want to render to a desktop window and instead send the data to another device, they use a wireless adapter as an example. Until I get time to learn how this works, have you checked out https://github.com/ValveSoftware/virtual_display ?
