### ISSUE TITLE
How to use physical HMD instead of null/virtual one

### ISSUE THREAD

**Issue by cheddarva** [terminal29/Simple-OpenVR-Driver-Tutorial#3]
Is there a way to modify the existing code so this driver will function with my Oculus Rift as the "Active HMD" instead of creating a null/dummy one?

I'm trying to develop a driver that modifies my HMD's projection matrix.

**Comment by terminal29** [comment]
To display on your rift, if it shows up as a monitor in your screen resolution settings then you just need to copy the offsets and resolution settings into the variables in the plugin and it should work as-is. As for the rotation and position of your headset, you're probably going to have to use the oculus' api and get your headsets pose that way.
