### ISSUE TITLE
Replace IVRControllerComponent with IVRDriverInput

### ISSUE THREAD

**Issue by claytmcneil** [terminal29/Simple-OpenVR-Driver-Tutorial#4]
It seems like the current version of the OpenVR API has changed the controller APIs in favor of IVRDriverInput. Any plans to update the tutorial?

**Comment by claytmcneil** [comment]
This change occurred starting in OpenVR SDK 1.0.12.

**Comment by claytmcneil** [comment]
Sure, let me know if I can help. I'm working through an example with latest version of the lib but ran into an issue. (https://github.com/ValveSoftware/openvr/issues/788 if you're curious).

**Comment by r57zone** [comment]
It would be cool to add an example of button emulation like [this](https://github.com/r57zone/OpenVR-driver-for-DIY/blob/master/OpenVR/samples/driver_sample/driver_sample.cpp#L494-L532).
