### ISSUE TITLE
Any chance of Getting Dummy lighhouse?

### ISSUE THREAD

**Issue by honzapatCZ** [terminal29/Simple-OpenVR-Driver-Tutorial#5]
Even if its object that will be once created and will just sit there and report to steamvr thats some basestation is connected and be visible with model in game please.

**Comment by terminal29** [comment]
Sure, I am planning on completely rewriting and updating the guide when Uni finishes for this year.

**Comment by honzapatCZ** [comment]
So when will it happen?

**Comment by terminal29** [comment]
Sorry, but I don't have plans to add anything more to this. Initializing a controller-type device as a `vr::TrackedDeviceClass_TrackingReference` is probably all you need to do though.
