### ISSUE TITLE
SteamVR Device Error (209) due to incompatibility

### ISSUE THREAD

**Issue by gabriel-combe** [terminal29/Simple-OpenVR-Driver-Tutorial#6]
Hello,

I try to create my own driver for my HMD and when I follow exactly the tutorial, an error occure, and says that the driver I use is not compatible with the actual version of SteamVR (1.5.16).
Have you any idea which part of the code are obsolete ?
vrmonitor logs:
![image](https://user-images.githubusercontent.com/26323828/61471705-804f4780-a983-11e9-8c2f-4364e0997f6e.png)

vrserver logs:
![image](https://user-images.githubusercontent.com/26323828/61472004-e20fb180-a983-11e9-83f6-8332420b808a.png)

**Comment by terminal29** [comment]
Do you have a link to your source?
