### ISSUE TITLE
Fake controller issue 

### ISSUE THREAD

**Issue by khail-k** [terminal29/Simple-OpenVR-Driver-Tutorial#7]
Hi,

I got two errors when building the latest code:

    'sin': is not a member of 'std'
    'cos': is not a member of 'std'

I solved it by adding ` #include <cmath> ` to **FakeController.cpp** and **FakeTracker.cpp**.

I thought this might be a bug as I am using the latest SDK, but I did not want to make a new branch for two lines.

**Comment by gabriel-combe** [comment]
Indeed, I also had this error with the last SDK, however I solved it by removing "std::" in front of the cos and the sin.
It seems that in the new versions of c++, the trigonometric functions are pre-integrated.

**Comment by terminal29** [comment]
Strange, for me it builds fine without it. Thanks for catching that though.
