### ISSUE TITLE
Please help: Everything breaks on this->AddDevice

### ISSUE THREAD

**Issue by AkayabeKimitsu** [terminal29/Simple-OpenVR-Driver-Tutorial#8]
Hello!
I was trying to use CMAKE version, built with visual studio,
(second time i just used cmake)
and everything was fine until i ran steamvr.
it just crashes.
But...
When i comment out lines with this->addevice etc. in init functon,
driver runs just fine (cause it have nothing to do)
But when i uncomment just single operation, it's just unrealiable to launch svr with it.
i have tried using those headers and adding them to normal vcxproj dll project,
but same actions there.
(I am trying to add base stations, so i don't really need any input files,
but it is not connected with issue with orginal buil;d with cmakelists)
so then..
please share something, that could be helpful.
i have even tried manual initialization of class, but still nothing to do with it.
Thanks for possible help!

**Comment by terminal29** [comment]
Ok just a couple questions:
- Does it throw an exception or is it a segfault? 
  - If yes, please send the log.
- Does it crash on every addDevice call ?
- Does it crash every time or only randomly ?
- What line does it crash on ? (I suspect it might be `vr::VRServerDriverHost()->TrackedDeviceAdded` but I'm not sure)

**Comment by terminal29** [comment]
Could you also include the `vrserver,txt` log file from C:\Program Files (x86)\Steam\logs

**Comment by AkayabeKimitsu** [comment]
Idk what was it, but it just doesn't work (i think it's my fault, idk using newest cmake, new svr?).
But i have used hipstersloth version (psmovesteamvrbridge) and it just works.
Thank you for fast help.
Cosing issue.

**Comment by AkayabeKimitsu** [comment]
Hello!
I have finally setup your code to work,
as i wrote it was only my fault.
It's nice, but even that, base stations tell me 'Searching...' and tell that they cannot find devices.
I have put them far from hmd and controllers, on initaialization, 
pointing at them, to they should work, but they doesn't.
Could you tell me anything that could help?
please...

**Comment by AkayabeKimitsu** [comment]
Ok. resolved.
I just need to do trackeddeviceposeupdated every frame and not let it crash.
thanx
